apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
      - key: "kubernetes.io/hostname"
        operator: "Equal"
        value: "mail"
      securityContext:
        fsGroup: 65534
      containers:
      - name: mail
        image: ghcr.io/erebe/email:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 25
        - containerPort: 143
        env:
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dovecot-users-password
              key: SMTP_PASSWORD
        - name: GANDI_RELAI_URL
          valueFrom:
            secretKeyRef:
              name: dovecot-users-password
              key: GANDI_RELAI_URL
        volumeMounts:
        - name: email-tls
          mountPath: /etc/dovecot/private/
          readOnly: true
        - name: dovecot-users-password
          mountPath: /etc/dovecot/users/
          readOnly: true
        - name: mail-data
          mountPath: /data
        - name: fetchmail
          mountPath: /etc/fetchmail
      volumes:
      - name: email-tls
        secret:
          secretName: email-tls
      - name: dovecot-users-password
        secret:
          secretName: dovecot-users-password
      - name: fetchmail
        configMap:
          name: fetchmail
          items:
          - key: fetchmailrc
            path: fetchmailrc
      - name: mail-data
        persistentVolumeClaim:
          claimName: mail-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-pv-claim
spec:
  storageClassName: nfs-nvme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: email-tls
spec:
  # Secret names are always required.
  secretName: email-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  subject:
    organizations:
    - erebe
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - mail.erebe.eu
  - erebe.eu
  # Issuer references are always required.
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
