apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "0 2 * * *" 
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          tolerations:
          - key: "kubernetes.io/hostname"
            operator: "Equal"
            value: "server"
          containers:
          - name: backup
            image: alpine
            args:
            - /bin/sh
            - -c
            - |- 
              set -ex
              apk add --no-cache lftp curl tar zstd openssl
              cd /tmp_dir
              tar -c -I 'zstd -3 -T1' -vf - /data | openssl enc -aes-256-cbc -pbkdf2 -iter 100000 -k ${ENCRYPTION_KEY} -e > backup.tar.zst.enc 
              # To decrypt openssl enc -aes-256-cbc -pbkdf2 -iter 100000 -k 'xxxxxxxx' -d -in backup.tar.zst.enc | tar x --zstd
              lftp -u ${USER},${PASSWORD} dedibackup-dc3.online.net -e 'put backup.tar.zst.enc -o /backups/backup_neo.tar.zst.enc; mv backups/backup_neo.tar.zst.enc backups/backup.tar.zst.enc; bye'
              curl https://hc-ping.com/9e922a32-947e-4f5c-9359-25d205531347
            env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: ftp-credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ftp-credentials
                  key: password
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: ftp-credentials
                  key: encryption-key
            volumeMounts:
            - name: data
              mountPath: /data
            - name: tmp-dir
              mountPath: /tmp_dir
          restartPolicy: OnFailure
          volumes:
          - name: data
            hostPath: 
              path: /opt
              type: Directory
          - name: tmp-dir
            emptyDir: {}
